#!/bin/sh

PROGRAM=/mnt/us/zman/zman.sh
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8


do_program()
{
	if [[ -f "$PROGRAM" ]]; then
	  $PROGRAM calculate
	fi
}

wake_program()
{
	if [[ $(lipc-get-prop com.lab126.powerd state) == screenSaver ]] && [[ -f "$PROGRAM" ]]; then
	  $PROGRAM calculate
	fi
}

run_program()
{
	if [[ -f "$PROGRAM" ]]; then
	  $PROGRAM run
	fi
}

lipc-wait-event -m com.lab126.powerd goingToScreenSaver,resuming,readyToSuspend | while read event; do
	case "$event" in
		goingToScreenSaver*)
			do_program;;
		resuming*)
			wake_program;;
		readyToSuspend*)
			run_program;;
	esac
done;

