#!/bin/sh

#####
# Copyright (c) 2019 Y Paritcher
#####

_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}
WORKDIR=/mnt/us/zman
KZMAN=$WORKDIR/kzman
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8


do_zman()
{
	if [[ -f "$KZMAN" ]]; then
		$KZMAN
		msg "zman: new picture" I
	fi
}

wake_zman()
{
	if is_PowerD_Sleeping; then
	  do_zman
	fi
}

run_zman()
{
	if [[ -f "$KZMAN" ]]; then
		$KZMAN delta
		msg "zman: delta" I
	fi
}

lipc-wait-event -m com.lab126.powerd goingToScreenSaver,resuming,readyToSuspend | while read event; do
	case "$event" in
		goingToScreenSaver*)
			do_zman;;
		resuming*)
			wake_zman;;
		readyToSuspend*)
			run_zman;;
	esac
done;

