#!/bin/sh

#####
# Copyright (c) 2019 Y Paritcher
#####

WORKDIR=/mnt/us/zman
KZMAN=$WORKDIR/kzman
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
kzmanarg="zman"

do_zman()
{
	if [[ -f "$KZMAN" ]]; then
		$KZMAN "$kzmanarg"
		logger -t "kzman[$$]" -p local4.info "I $kzmanarg: new picture"
		case "$kzmanarg" in
			zman)
				kzmanarg="shuir";;
			shuir)
				kzmanarg="zman";;
		esac
	fi
}

wake_zman()
{
	logger -t "kzman[$$]" -p local4.info "I wakeup run"
	POWERD_STATES=`lipc-get-prop -s com.lab126.powerd state`
	logger -t "kzman[$$]" -p local4.info "I PowerD state: $POWERD_STATES"
	if [ "$POWERD_STATES" == "screenSaver" ] || [ "POWERD_STATES" == "suspended" ] ; then
	  do_zman
	fi
}

run_zman()
{
	if [[ -f "$KZMAN" ]]; then
		$KZMAN delta
		logger -t "kzman[$$]" -p local4.info "I delta"
	fi
}

lipc-wait-event -m com.lab126.powerd goingToScreenSaver,wakeupFromSuspend,readyToSuspend | while read event; do
	case "$event" in
		goingToScreenSaver*)
			do_zman;;
		wakeupFromSuspend*)
			wake_zman;;
		readyToSuspend*)
			run_zman;;
	esac
done;

