#!/bin/sh

#####
# Copyright (c) 2019 Y Paritcher
#####

_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}


KZMAND=/usr/local/bin/zman_backround

start()
{
	msg "starting zman" I
	$STARTSTOPD -q -x $KZMAND -S -b
}

stop()
{
	msg "stopping zman" I
	pkill -x -f "lipc-wait-event -m com.lab126.powerd goingToScreenSaver resuming readyToSuspend"
}

case "$1" in

	start)
		start
		;;

	stop)
		stop
		;;
	
	restart)
		stop
		start
		;;
	
	status)
		stop
		;;

	*)
		msg "Usage: $0 start" W
		exit 1
		;;
esac

exit 0

