#!/bin/bash

#####
# Copyright (c) 2019 Y Paritcher
#####

convert -density 167 -depth 8 -size 600x30 canvas:lightgrey -fill black  -font ../zman/ezra.ttf -pointsize 10 -gravity NorthEast -annotate +30+0 'ב"\ה'  -stroke black -strokewidth 6 -draw "line 0,30 600,30" 000.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 010.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 020.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 030.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 040.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 050.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 060.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 070.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 080.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 090.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 100.png
convert -density 167 -depth 8 -size 600x70 canvas:lightgrey  -stroke black -strokewidth 6 -draw "line 0,70 600,70" 110.png

convert -density 167 -depth 8 [0-9][0-9]0.png -append -stroke black -strokewidth 6 -draw "line 0,0 0,800" -draw "line 600,0 600,800" -draw "line 0,0 600,0" ../zman/bgpicshuir.png

rm ./[0-9][0-9]0.png
